name: Host

on:
  push:
    branches: [main, data]
  workflow_dispatch:

concurrency:
  group: host
  cancel-in-progress: true

env:
  JAVA_DISTRIBUTOR: temurin # https://github.com/actions/setup-java#supported-distributions
  JAVA_VERSION: 21 # https://minecraft.wiki/w/Tutorial:Setting_up_a_server#Java_version
  MINECRAFT_SERVER_TYPE: vanilla # https://mcutils.com/server-jars
  MINECRAFT_VERSION: 1.21.4 # https://minecraft.wiki/w/Java_Edition_version_history

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTOR }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Download data
        uses: actions/checkout@v4
        with:
          ref: data

      - name: Set up server
        run: curl -L "https://mcutils.com/api/server-jars/${{ env.MINECRAFT_SERVER_TYPE }}/${{ env.MINECRAFT_VERSION }}/download" -o server.jar

      - name: Run server
        run: |
          cloudflared tunnel --url localhost:25565/ &
          java -Xmx1024M -Xms1024M -jar server.jar nogui
