name: Host

on:
  push:
    branches: [main, data]
  workflow_dispatch:

concurrency:
  group: host
  cancel-in-progress: true

env:
  JAVA_DISTRIBUTOR: temurin # https://github.com/actions/setup-java#supported-distributions
  JAVA_VERSION: 21 # https://minecraft.wiki/w/Tutorial:Setting_up_a_server#Java_version
  MINECRAFT_SERVER_TYPE: vanilla # https://mcutils.com/server-jars
  MINECRAFT_VERSION: 1.21.4 # https://minecraft.wiki/w/Java_Edition_version_history
  MINECRAFT_PORT: 25565

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTOR }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download data
        uses: actions/checkout@v4
        with:
          ref: data

      - name: Set up server
        run: curl -L "https://mcutils.com/api/server-jars/${{ env.MINECRAFT_SERVER_TYPE }}/${{ env.MINECRAFT_VERSION }}/download" -o server.jar

      - name: Set up ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
            && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list \
            && sudo apt update \
            && sudo apt install ngrok

          ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Start server
        run: |
          ngrok http http://localhost:${{ env.MINECRAFT_PORT }} &
          java -Xmx1024M -Xms1024M -jar server.jar nogui
