name: Host

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - run: java --help
